server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5434/course
    username: "postgres"
    password: "root"
  jpa:
    hibernate:
      #      criar tabelas automatico
      ddl-auto: update
      dialect: org.jibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    serviceUrl:
      defaultzone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost